matrimonial-interface/config/routes.rb
Rails.application.routes.draw do
  root "pages#about"
  resources :images
  resources :users
  resources :sessions
  resources :profiles
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'pages#index'
end

matrimonial-interface/app/models/profile.rb
class Profile < ApplicationRecord
    # validates :name, :age, :gender, :location, presence: true
    belongs_to :user, class_name: "User", foreign_key: "user_id"
end

matrimonial-interface/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  # def index
  #   @profiles = Profile.all
  # end
  def index 
    @profiles = Profile.order(params[:sort]).reverse
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    @profile.user_id = @profile.id
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile.user_id = @profile.id
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :age, :gender, :location, :cultureScore, :facialScore, :lifestyleScore, :kundaliScore, :locationScore)
    end
end

matrimonial-interface/app/helpers/profiles_helper.rb
module ProfilesHelper
end

matrimonial-interface/app/views/profiles/_form.html.erb
<%= form_with model: @profile do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :cultureScore %>
    <%= form.text_field :cultureScore %>
  </div>

  <div class="field">
    <%= form.label :facialScore %>
    <%= form.text_field :facialScore %>
  </div>

  <div class="field">
    <%= form.label :lifestyleScore %>
    <%= form.text_field :lifestyleScore %>
  </div>

  <div class="field">
    <%= form.label :kundaliScore %>
    <%= form.text_field :kundaliScore %>
  </div>

  <div class="field">
    <%= form.label :locationScore %>
    <%= form.text_field :locationScore %>
  </div>

<%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

matrimonial-interface/app/views/profiles/_profile_card.html.erb
<% @profiles.each do |profile| %>
  <div class="card mx-auto" style="min-width: 15rem; max-width: 15rem;">
    <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= profile.name %></h5>
      <p class="card-text">Age: <%= profile.age %></p>
      <p class="card-text">Location: <%= profile.location %></p>
      <%= link_to "View", profile, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

matrimonial-interface/app/views/profiles/_profile_card_wide.html.erb
<% @profiles.each do |profile| %>
  <div class="card" style="width: 80vw; height: 10vh; margin: 0;">
    <div class="card-body">
      <h5 class="card-title" style="margin: 0;"><%= profile.name %></h5>
      <p class="card-text" style="margin: 0;">Age: <%= profile.age %></p>
      <p class="card-text" style="margin: 0;">Location: <%= profile.location %></p>
    </div>
  </div>
<% end %>

matrimonial-interface/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

matrimonial-interface/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pie Chart Test</h1>

<%= javascript_pack_tag 'draggable-piechart-jquery' %>
    <div>
        <canvas id="piechart" width="400" height="400"></canvas>

        <table id="proportions-table">
            <tbody>
                <tr>
                    <td>
                        <var>23%</var>
                    </td>
                    <td>
                        <var>12%</var>
                    </td>
                    <td>
                        <var>16%</var>
                    </td>
                    <td>
                        <var>34%</var>
                    </td>
                    <td>
                        <var>15%</var>
                    </td>
                </tr>
                <br>
                <tr>
                    <th>Culture</th>
                    <th>FR</th>
                    <th>Lifestyle</th>
                    <th>Kundali</th>
                    <th>Location</th>
                </tr>
            </tbody>
        </table>
    </div>

<h1>Profiles</h1>

<div class="container mx-auto">
  <div class="card mx-auto">
    <br>

    <span id="pieSortSpan"><% pieSort(3, 1, 1, 1, 1) %></span>
    <%= render 'profile_card_wide' %>
    <br>
  </div>
</div>
<br>
<br>

<h1>Table</h1>
<table>
  <tr>
    <th>Name</th> 
    <th><%= link_to "Culture Score", :sort => "cultureScore"%> </th>  
    <th><%= link_to "FR Score", :sort => "facialScore"%> </th>
    <th><%= link_to "Lifestyle Score", :sort => "lifestyleScore"%> </th>
    <th><%= link_to "Kundali Score", :sort => "kundaliScore"%> </th>
    <th><%= link_to "Location Score", :sort => "locationScore"%> </th>   
  </tr>
 <% @profiles.each do |profile| %>
  <tr>
    <td><%=profile.name%></td>
    <td><%=profile.cultureScore%></td>
    <td><%=profile.facialScore%></td>
    <td><%=profile.lifestyleScore%></td>
    <td><%=profile.kundaliScore%></td>
    <td><%=profile.locationScore%></td>
  </tr>
  <% end %>
 </table>

<br>
<br>
<br>
<br>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Admin Controls</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <style>
        table {
            border-collapse: collapse;
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            user-select: none;
            display: inline;
        }

        .color-label {
            width: 10px;
            height: 10px;
            background-color: aqua;
        }

        td {
            width: 150px;
        }

        var {
            width: 50px;
            display: inline-block;
            align-items: center;
        }
    </style>

    <script>
        (function () {

            //IE9+ http://youmightnotneedjquery.com/
            function ready(fn) {
                if (document.attachEvent ? document.readyState === "complete" : document.readyState !== "loading") {
                    fn();
                } else {
                    document.addEventListener('DOMContentLoaded', fn);
                }
            }

            ready(setupPieChart);


            function setupPieChart() {

                let labelsArray = ['Culture', 'Facial Recognition', 'Lifestyle', 'Kundali', 'Location'];
                var dimensions = labelsArray;
                let colorsArray = ['#ff99ee', '#11aaff', '#ffff00', '#00ff99', '#bb00ee'];
                var equalProportions = 20;
                var proportions = dimensions.map(function (d, i) {
                    return {
                        label: d,
                        proportion: equalProportions,
                        collapsed: false,
                        format: {
                            color: colorsArray[i], label: d.charAt(0).toUpperCase() + d.slice(1), // capitalise first letter
                        }
                    }
                });

                var setup = {
                    canvas: document.getElementById('piechart'),
                    radius: 0.9,
                    collapsing: false,
                    proportions: proportions,
                    drawSegment: drawSegmentOutlineOnly,
                    onchange: onPieChartChange
                };

                var newPie = new DraggablePiechart(setup);

                function drawSegmentOutlineOnly(context, piechart, centerX, centerY, radius, startingAngle, arcSize, format, collapsed) {

                    if (collapsed) { return; }

                    // Draw segment
                    context.save();
                    var endingAngle = startingAngle + arcSize;
                    context.beginPath();
                    context.moveTo(centerX, centerY);
                    context.arc(centerX, centerY, radius, startingAngle, endingAngle, false);
                    context.closePath();

                    context.fillStyle = format.color;
                    context.fill();
                    context.stroke();
                    context.restore();

                    // Draw label on top
                    context.save();
                    context.translate(centerX, centerY);
                    context.rotate(startingAngle);

                    var fontSize = Math.floor(context.canvas.height / 40);
                    var dx = radius - fontSize;
                    var dy = centerY / 10;

                    context.textAlign = "right";
                    context.font = fontSize + "pt Fira Code";
                    context.fillText(format.label, dx, dy);
                    context.restore();
                }

                function onPieChartChange(piechart) {

                    var table = document.getElementById('proportions-table');
                    var table2 = document.getElementById('proportions-table2');
                    var percentages = piechart.getAllSliceSizePercentages();

                    var labelsRow = '<tr>';
                    var propsRow = '<tr>';
                    for (var i = 0; i < proportions.length; i += 1) {
                        labelsRow += '<th>' + proportions[i].format.label + '</th>';
                        
                        var v = '<var>' + percentages[i].toFixed(0) + '%</var>';
                        var plus = '<div id="plu-' + dimensions[i] + '" class="adjust-button" data-i="' + i + '" data-d="-1"></div>';
                        var minus = '<div id="min-' + dimensions[i] + '" class="adjust-button" data-i="' + i + '" data-d="1"></div>';
                        propsRow += '<td>' + v + plus + minus + '</td>';
                        var updatePercent = percentages[i].toFixed(0);
                        updateTable2(updatePercent);
                    }

                    function updateTable2(v) {
                        console.log(i, " ", v);
                        var v = '<var>' + percentages[i].toFixed(0) + '%</var>';

                        // var c = v;
                        // if (c < 20) {
                        //     var ps = '<span id="pieSortSpan"><%= pieSort(1, 1, 1, 1, 1) %> </span>';
                        // } else if (c >= 20 && c < 40) {
                        //     var ps = '<span id="pieSortSpan"><%= pieSort(2, 1, 1, 1, 1) %> </span>';
                        // } else if (c >= 40 && c < 60) {
                        //     var ps = '<span id="pieSortSpan"><%= pieSort(3, 1, 1, 1, 1) %> </span>';
                        // } else if (c >= 60 && c < 80) {
                        //     var ps = '<span id="pieSortSpan"><%= pieSort(4, 1, 1, 1, 1) %> </span>';
                        // } else if (c >= 80 && c < 1000) {
                        //     var ps = '<span id="pieSortSpan"><%= pieSort(5, 1, 1, 1, 1) %> </span>';
                        // }
                        
                    }

                    $('#pieSortSpan').html('<%escape_javascript(pieSort(3, 1, 1, 1, 1)) %>');

                    labelsRow += '</tr>';
                    propsRow += '</tr>';
                    table.innerHTML = labelsRow + propsRow;
                    var adjust = document.getElementsByClassName("adjust-button");

                    function adjustClick(e) {
                        var i = this.getAttribute('data-i');
                        var d = this.getAttribute('data-d');
                        piechart.moveAngle(i, (d * 0.1));
                    }

                    for (i = 0; i < adjust.length; i++) {
                        adjust[i].addEventListener('click', adjustClick);
                    }
                }
            }
        })();

    </script>

matrimonial-interface/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

matrimonial-interface/app/views/profiles/show.html.erb
<h2 class="text-center mt-4"><%= @profile.name %></h2>
<div class="container-fluid mx-auto">
  <div class="card mx-auto" style="width: 80vw;">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="false">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active rounded">
          <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" class="img-fluid" style="max-width: 25vw;" alt="...">
        </div>
        <div class="carousel-item rounded">
          <img src="https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png" class="img-fluid" style="max-width: 25vw;" alt="...">
        </div>
        <div class="carousel-item rounded">
          <img src="https://cdn.iconscout.com/icon/free/png-256/user-1648810-1401302.png" class="img-fluid" style="max-width: 25vw;" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    
    <div class="card-body">
      <h5 class="card-title"><%= @profile.name %></h5>
      <p class="card-text">Age: <%= @profile.age %></p>
      <p class="card-text">Gender: <%= @profile.gender %></p>
      <p class="card-text">Location: <%= @profile.location %></p>
      <p class="card-text">User ID: <%= @profile.user_id %></p>
      <p class="card-text">Culture Score: <%= @profile.cultureScore %></p>
      <p class="card-text">Facial Score: <%= @profile.facialScore %></p>
      <p class="card-text">Lifestyle Score: <%= @profile.lifestyleScore %></p>
      <p class="card-text">Kundali Score: <%= @profile.kundaliScore %></p>
      <p class="card-text">Location Score: <%= @profile.locationScore %></p>
      
      <% if logged_in? && current_user_profile.user_id == current_user.id %>
        <%= link_to "Edit", edit_profile_path(@profile), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>