matrimonial-interface/config/routes.rb
Rails.application.routes.draw do
  root "pages#about"
  resources :images
  resources :users
  resources :sessions
  resources :profiles
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'pages#index'
end

matrimonial-interface/app/models/image.rb
class Image < ApplicationRecord
    has_one_attached :file
    belongs_to :user
end

matrimonial-interface/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy, :add]


  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
    @image = current_user.images.build
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.new(image_params)
      respond_to do |format|
        if @image.save
          format.html { redirect_to @image, notice: 'Image was successfully created.' }
          format.json { render :show, status: :created, location: @image }
        else
          format.html { render :new }
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def acceptable_file
    return unless file.attached?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:file, :title, :description, :user)
    end
end

matrimonial-interface/app/helpers/images_helper.rb
module ImagesHelper
end

matrimonial-interface/app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

</p>

  <div>
    <%= form.file_field :file %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Upload Image" %>
  </div>
<% end %>

matrimonial-interface/app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

matrimonial-interface/app/views/images/index.html.erb
<%= stylesheet_link_tag "style_Index" %>

<p id="notice"><%= notice %></p>

<h2>Welcome to the<h2>
<h1>Matrimonial Interface</h1>
<br>
<%
=begin%>
 <table> 
<%
=end%>
  <%
=begin%>
 <tbody class="user-grid"> 
<%
=end%>
  <div class="user-grid">
    <% @images.each do |image| %>
        <%= link_to image_tag(image.file.variant(resize_to_limit: [nil, 150])), image %>
    <% end %>
    </div>
  <%
=begin%>
 </tbody> 
<%
=end%>
<%
=begin%>
 </table> 
<%
=end%>

<br>

<%
=begin%>
 <%= link_to 'New Image', new_image_path %> 
<%
=end%>

matrimonial-interface/app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

matrimonial-interface/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Title: <%= @image.title %></h1>

<%= image_tag(@image.file.variant(resize_to_limit: [500, nil])) %>
<h3>Description: <%= @image.description %></h3>

<table>
  <tbody>
      <tr>
        <td><%= link_to 'Home', root_path %></td>
        <td><%= link_to 'Edit', edit_image_path(@image) %></td>
        <td><%= link_to 'Delete', @image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>