matrimonial-interface/config/routes.rb
Rails.application.routes.draw do
  root "pages#about"
  resources :images
  resources :users
  resources :sessions
  resources :profiles
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'pages#index'
end

matrimonial-interface/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 text-white">
    <div class="container text-center">
        <small>Matrimonial Interface 2021</small>
    </div>
</footer>

matrimonial-interface/app/views/layouts/_navigation.html.erb
<nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "M-I", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Profiles", profiles_path, class: "nav-link" %>
            </li>
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to current_user_profile.name, profile_path(current_user_profile), class: "nav-link", method: :delete %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', signup_path, class: "nav-link" %>
            </li>
          <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profile
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if logged_in? %>
                  <%= link_to "View Profile", current_user_profile, class: "dropdown-item" %>
                <% end %>
                <!-- <li><a class="dropdown-item" href="#">Action</a></li> -->
                <% if logged_in? %>
                  <%= link_to "Edit Profile", edit_profile_path(current_user_profile), class: "dropdown-item" %>
                <% end %>
                <!-- <li><a class="dropdown-item" href="#">Another action</a></li> -->
                <!-- <li><hr class="dropdown-divider"></li> -->
                <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
              </ul>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
</nav>
<br>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

matrimonial-interface/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M-I</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  </head>
  
  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>